Repository hackclub/winter, pull requests merged in 2023-01, with the labels that each got.

#110 Portable Multifunction Device
  MangoTornado.md
Labels: project

#139 Modern Duck Hunt & NES Zapper
  DevIos01&Kiana.md
Labels: project

#193 Adding Sweden as eligible countries
  docs/eligible_countries.md
Labels: documentation

#154 initial proposal
  citricacid2.md
Labels: project

#117 Add Missing Items and Microphone to KaiDevrim
  KAIDEVRIM.md
  KaiDevrim.md
Labels: project

#114 Added ArduinArm!
  skumm00.md
Labels: project

#145 Create Divya-2009.md
  Divya-2009.md
Labels: project

#97 Create Dhruv561.md
  Dhruv561.md
Labels: project

#146 create andy-phung.md!
  andy-phung.md
Labels: project

#116 45% Keyboard
  sohamb117.md
Labels: project

#18 Create khrj.md
  khrj.md
Labels: project

#149 Spotify Desk Thing
  peiprjs.md
Labels: project

#153 rcyaon.md
  rcyaon.md
Labels: project

#133 My request :3
  l3gacyb3ta.md
Labels: project

#101 Amir's SleepBuddy2 project
  LiricTech.md
Labels: project

#113 Gesture Control Robot
  ManikShrivastav.md
Labels: project

#148 Create HarjotSuiingh.md
  HarjotSuiingh.md
Labels: project

#135 KrishnaSharma206
  KrishnaSharma206.md
Labels: project

#132 Add Urban Kayak Project Proposal
  thekyleliao.md
Labels: project

#142 Create Kevin-Liu-01.md
  Kevin-Liu-01.md
Labels: project

#112 Colorblind Drivers + ML and Motion Lights
  CoolCoderSJ.md
Labels: project

#161 Face Following Robot
  bikash159.md
Labels: project

#143 Create amishasao.md
  amishasao.md
Labels: project

#157 sofiykam.md
  sofiykam.md
Labels: project

#141 Shawn Malluwa Proposal
  Shawn Malluwa.md
Labels: project

#304 Split-flap display: linkai101
  linkai101.md
Labels: project

#62 3-Axis Robotic Arm
  Screen-sLaYeR.md
Labels: project

#134 Glucose Monitoring Project
  Bhoomi-2115.md
Labels: project

#287 Update samarth641.md
  samarth641.md
Labels: project

#399 Create tregsthedev.md
  tregsthedev.md
Labels: project

#332 Roh101.md
  Roh101.md
Labels: project

#385 Create shojha24.md
  shojha24.md
Labels: project

#367 Sprig gaming controller
  cytronicoder.md
Labels: project

#409 Smart alarm clock
  YodaLightsabr.md
Labels: project

#356 Interactive Digital Art Installation + MIDI Controller
  Amagtoto.md
Labels: project

#294 Create kaiz715.md
  kaiz715.md
Labels: project

#292 The TodayDisplay
  Spartoons.md
Labels: project

#316 Create Create AHussein04.md
  Create AHussein04.md
Labels: project

#354 adds split keyboard
  ex4722.md
Labels: project

#299 Smart RC Car With AI Camera
  TheScientist101.md
Labels: project

#322 GPS tracking system
  chrisrama.md
Labels: project

#403 Monopoly Tablet
  KianTheCon.md
Labels: project

#325 println("ZeroQL's project")
  ZeroQLi.md
  euphorichubbbb.md
Labels: project

#302 Create sebrod06.md
  sebrod06.md
Labels: project

#298 Temperature Monitor
  griffinli.md
Labels: project

#364 Budget Updated
  AEZ314.md
Labels: bankops

#413 Create Tanishqupmanu.md
  Tanishqupmanu.md
Labels: project

#267 Create shreekar-developer.md
  shreekar-developer.md
Labels: project

#347 Create snoglobe.md
  snoglobe.md
Labels: project, bankops

#342 Create CatR3kd.md
  CatR3kd.md
Labels: project, bankops

#237 Create ristonrodrigues723.md
  ristonrodrigues723.md
Labels: project, bankops

#301 Create abhisinghh501.md
  abhisinghh501.md
Labels: project, bankops

#402 Create srinathn07.md
  srinathn07.md
Labels: project, bankops

#397 Create DevinGagnon&
  DevinGagnon&Matt&elliot.md
Labels: project, bankops

#388 Belizairebr25.md
  belizairebr25.md
Labels: project, bankops

#288 6" FPV Drone
  rutujsune.md
Labels: project, bankops

#406 Create tejasCreative.md
  tejascreative.md
Labels: project, bankops

#353 xhaidendsouza 3d mechanically coded robot
  xhaidendsouza.md
Labels: project

#359 create ahussain23
  ahussain23V3.md
Labels: project, bankops

#317 Weather Lamp
  esjiko.md
Labels: project, bankops

#345 Create Custom Antennas
  Custom-Antennas.md
Labels: project, bankops

#395 Create hchristy1234.md
  hchristy1234.md
Labels: project, bankops

#346 Add nickkbuii
  nickkbuii.md
Labels: project, bankops

#351 Plant Watering System 🌱
  blobbybilb.md
Labels: project, bankops

#355 PianoBot
  thatdevhuddy.md
Labels: project, bankops

#334 Create Raymond131&MarcoKurepa.md
  Raymond131&MarcoKurepa.md
Labels: project, bankops

#336 Custom 6DOF Robot Camera Arm
  andrwwz.md
Labels: project, bankops

#206 pikca-c's project
  pikca-c.md
Labels: project, bankops

#174 Create GurshanBrar.md
  GurshanBrar.md
Labels: project, bankops

#159 Created AceGreenJay.md
  Captain-AJ.md
Labels: project, bankops

#393 Bedroom Security System
  wollygfx.md
Labels: project, bankops

#382 Add jianmin-chen.md
  jianmin-chen.md
Labels: project, bankops

#326 🌈 🪩 ✨ Gramophone-502x!
  neiltheghosh&arshshrivastavaa&sampoder.md
Labels: project, bankops

#167 Custom QMK Firmware Keyboard
  AidenRheem.md
Labels: project, bankops

#407 Self driving electric bike
  pranavnt-quackduck.md
Labels: project, bankops

#350 whatwareweb
  whatwareweb.md
Labels: project, bankops

#386 Create zoya-hussain.md
  zoya-hussain.md
Labels: project, bankops

#408 Project Oreo: DIY Cheap USB Rubber Duckies
  karmanyaahm.md
Labels: project, bankops

#380 Foosball scoreboard
  reesericci.md
Labels: project, bankops

#343 Create vincent_doan
  TheTsar8756.md
Labels: project, bankops

#328 Rachwel
  rachwel.md
Labels: project, bankops

#286 Create xi-forgetme.md
  xi-forgetme.md
Labels: project, bankops

#436 [veeby deeby] budget update woop woop
  cfanoulis.md
Labels: project

#289 RC Quadcopter DIY
  btechboy.md
Labels: project, bankops

#360 Create Steve-Dusty.md
  Steve-Dusty.md
Labels: project, bankops

#349 Create chicken-in-a-can.md
  chicken-in-a-can.md
Labels: project, bankops

#291 Create BogdanShemetov.md
  BogdanShemetov.md
Labels: project, bankops

#140 3D printed mechanical keyboard
  iwang1.md
Labels: project, bankops

#306 Create ahnedmohamed57.md
  ahnedmohamed57.md
Labels: project, bankops

#423 smart Mirror
  SantoshiUser1.md
Labels: project, bankops

#300 Smart home System!
  ProbablySwifty.md
Labels: project, bankops

#363 AI Assistant home automation system
  innovativecreations.md
Labels: project, bankops

#440 Updated Price Estimates and Component Breakdown
  galadrielmccrea.md
Labels: bankops, project-update

#224 Tron Hoodie
  Mahak1729
Labels: project, project-accepted, bankops, unbanked

#358 Custom Keyboard Firmware
  samanthahuaaANDcourtneyhg.md
Labels: project, bankops

#240 Create DarthCoder501
  DarthCoder501
Labels: project, bankops

#434 6" FPV Drone Update
  rutujsune.md
Labels: project-update

#442 Update Project Proposal For IoT Plant Watering System
  Verisimilitude11.md
Labels: project-update

#321 rfid nfc wallet
  sol5000.md
Labels: project, bankops

#420 EpicCactus94 Updated PR
  EpicCactus94.md
Labels: project, bankops

#318 LED and Speaker Connected "Alarm"
  sai-nallani.md
Labels: project, bankops

#309 RC Drone ArnavK28
  ArnavK28.md
Labels: project, bankops

#404 qpong
  sheryylli.md
Labels: project, bankops

#392 ack :)
  bellesea.md
Labels: project, bankops

#54 Realistic Iron Man Helmet
  Ironman Helmet
Labels: project, bankops

#58 Home Security Drone
  relatedtitle.md
Labels: project, project-accepted, bankops

#415 LucidVR Haptic Gloves with RC Car and Robot Arm
  grammarfruit.md
Labels: project, bankops

#293 Create acornitum
  acornitum.md
Labels: project, bankops

#376 added BohemaRapsody.md
  BohemaRapsody.md
Labels: project, bankops

#327 Create Apoorv38.md
  Apoorv38.md
Labels: project, bankops

#437 Update Val171.md
  Val171.md
Labels: project-update
