Repository hackclub/winter, pull requests merged in 2023-02, with the labels that each got.

#341 Create adithyakommi.md
  adithyakommi.md
Labels: project, bankops

#375 Secure VPN Travel Router with own DNS & VPN server
  singhgurmehar.md
Labels: project, project-accepted, bankops

#371 ATL Notice Board
  vmss2009.md
Labels: project, bankops

#449 Update BogdanShemetov.md
  BogdanShemetov.md
Labels: bankops, project-update

#448 Update Spotify Desk Thing
  peiprjs.md
Labels: bankops, project-update

#447 Project Update
  samanthahuaaANDcourtneyhg.md
Labels: project-update

#424 AI-Powered RC Car
  SiruX21.md
Labels: project, project-accepted, bankops

#454 Budget Update: Add Second Hand Vinyl Record
  neiltheghosh&arshshrivastavaa&sampoder.md
Labels: project-update

#335 Create Sanjay Soldering
  sanjay-nagesh.md
Labels: project, bankops

#383 Create Gspidey123.md
  Gspidey123.md
Labels: project, bankops

#453 Another Project Update
  samanthahuaaANDcourtneyhg.md
Labels: project-update

#452 Change amplifier board
  whatwareweb.md
Labels: project-update

#319 Create christopherli574.md
  christopherli574.md
Labels: project, bankops

#391 Create vedhasirur.md
  vedhasirur.md
Labels: project, bankops

#368 IOT Display Device
  CreNiruta.md
Labels: project, bankops

#102 Winter
  Abubakarharuna10.md
Labels: project, bankops

#378 Create RishitaxGhosh.md
  RishitaxGhosh.md
Labels: project, bankops

#400 Create faheemam8102.md
  faheemam8102.md
Labels: project, bankops

#348 Self Hosted Home Assistant
  dishit79.md
Labels: project, bankops

#458 Add Courier Fees for Record
  neiltheghosh&arshshrivastavaa&sampoder.md
Labels: project-update

#438 Another item change
  pikca-c.md
Labels: bankops, project-update

#370 Voice controlled car
  priyamrugesan24.md
Labels: project, bankops

#445 Update Roizor.md
  Roizor.md
Labels: project-update

#439 personal tempate update and otherfixes (#439)Co-authored-by: Charalampos Fanoulis <charalampos.fanoulis@gmail.com>
  AHussein04.md
  AidenRheem.md
  AnishT500.md
  Apoorv38.md
  BogdanShemetov.md
  BohemaRapsody.md
  DarthCoder501.md
  Jackson-Turner.md
  ManikShrivastav.md
  ParthAgarwal.md
  Raymond131&MarcoKurepa.md
  Roh101.md
  SantoshiUser.md
  StevenJohnson12.md
  ZeroQLi.md
  abhisinghh501.md
  adithyakommi.md
  aleung18.md
  alihussain23.md
  chennisden.md
  christopherli574.md
  clive223.md
  darksidemanas.md
  docs/eligible_countries.md
  esjiko.md
  ethanc7.md
  hard-shutdown.md
  iwang-1.md
  karmanyaahm.md
  limeskey.md
  neiltheghosh&arshshrivastavaa&sampoder.md
  nickkbuii.md
  pranavnt&quackduck.md
  rachwel.md
  reesericci.md
  samanthahuaaANDcourtneyhg.md
  sanjus-robotic-studio.md
  shreekar-developer.md
  sswangg.md
Labels: zeroql made yet another pull request

#463 added ardunio (can change budget on bank?)
  sol5000.md
Labels: project-update
